project_id = "uvvaxwtumuabfklccjgd"

[functions.send-messages]
verify_jwt = true

[functions.test-connection]
verify_jwt = true

[functions.cleanup-files]
verify_jwt = false

[functions.fzap-create-instance]
verify_jwt = true

[functions.fzap-status]
verify_jwt = true

[functions.fetch-groups]
verify_jwt = true

[functions.send-group-messages]
verify_jwt = true
